# Machines without root (hosts.nix: noRoot), e.g. snoopy.
#
# nix-portable (bwrap runtime) keeps the Nix store in <location>/.nix-portable;
# it is visible as /nix only inside nix-portable's namespace. home-manager
# activates into a separate home (noRoot.home) instead of the real one, so the
# real ~ (its quota, its login shell, other tools) is never touched. The real
# ~/.zshrc enters the env on interactive logins with:
#
#   if [[ -o interactive && -z $IN_NIXSHELL && -z $NO_NIXSHELL \
#         && -x <location>/bin/nixshell && -d <location>/.nix-portable ]]; then
#     exec <location>/bin/nixshell
#   fi
#
# Whatever runs from outside the env (that hook, systemd, `ssh host cmd`) can't
# follow links into /nix/store, so activation writes these as real files:
#   <location>/bin/{nixshell,hm-switch,nix,dots-pull}
#   ~/.config/systemd/user/dots-sync.{service,timer} in the real home
# nix-portable itself (<location>/bin/nix-portable) is installed by
# scripts/bootstrap-no-root and left alone here.
{ config, lib, pkgs, host, ... }:
let
  cfg = host.noRoot;
  loc = cfg.location;
  bin = "${loc}/bin";
  realHome = cfg.realHome or "/home/${host.user}";
  target = "${host.user}@${host.name}";
  marker = "Generated by modules/no-root.nix";
  np = ''export NP_LOCATION=${loc} NP_RUNTIME=bwrap'';
  # home-manager's zsh, at a path that survives generations (inside the env).
  # It must be the one running the config: e.g. fzf-tab's compiled module is
  # linked against Nix's glibc and fails to load in the system zsh.
  zsh = "${config.home.profileDirectory}/bin/zsh";

  scripts = {
    nixshell = ''
      #!/bin/sh
      # ${marker}.
      # Enter the home-manager env (zsh with this config) inside nix-portable.
      # Exiting it ends the session like a normal login shell. nixpkgs#zsh only
      # gets us into the namespace; the login shell is home-manager's zsh, also
      # exported as SHELL so tmux panes etc. don't fall back to /usr/bin/zsh.
      ${np} IN_NIXSHELL=1 HOME=${cfg.home}
      # shellcheck disable=SC2016  # expanded by the inner zsh
      exec ${bin}/nix-portable nix shell nixpkgs#zsh --command zsh -fc \
        'z=${zsh}; [[ -x $z ]] || z=$(whence -p zsh); export SHELL=$z; exec $z -l'
    '';
    nix = ''
      #!/bin/sh
      # ${marker}.
      ${np}
      exec ${bin}/nix-portable nix "$@"
    '';
    hm-switch = ''
      #!/bin/sh
      # ${marker}.
      # Build and activate ${target} through nix-portable.  hm-switch [flake-dir]
      set -e
      ${np} HOME=${cfg.home}
      NP=${bin}/nix-portable
      FLAKE=''${1:-${cfg.flake}}
      echo "==> building ${target}"
      gen=$("$NP" nix build "$FLAKE#homeConfigurations.\"${target}\".activationPackage" \
        --no-link --print-out-paths --extra-experimental-features 'nix-command flakes')
      # Activation needs nix-env & co. on PATH. Use nix-portable's own Nix so a
      # newer Nix never upgrades the store database under it.
      v=$("$NP" nix --version | awk '{print $NF}')
      echo "==> activating $gen"
      # shellcheck disable=SC2016  # expanded by the inner bash
      exec "$NP" nix shell nixpkgs#bash --command bash -c '
        export PATH="$(echo /nix/store/*-nix-'"$v"'/bin):$PATH"
        exec bash "$1"
      ' hm "$gen/activate"
    '';
    dots-pull = builtins.replaceStrings [ "#!/usr/bin/env bash\n" ] [ "#!/usr/bin/env bash\n# ${marker}.\n" ]
      config.dots.pullScript;
  };
  scriptDir = pkgs.linkFarm "no-root-bin" (lib.mapAttrsToList (name: text: {
    inherit name;
    path = pkgs.writeText name text;
  }) scripts);

  units = pkgs.linkFarm "no-root-units" [
    { name = "dots-sync.service"; path = pkgs.writeText "dots-sync.service" ''
        [Unit]
        Description=Pull ${cfg.flake} from GitHub and apply it (nix-portable)

        [Service]
        Type=oneshot
        ExecStart=${bin}/dots-pull
      ''; }
    { name = "dots-sync.timer"; path = pkgs.writeText "dots-sync.timer" ''
        [Unit]
        Description=Hourly dotfiles pull

        [Timer]
        OnCalendar=hourly
        Persistent=true
        RandomizedDelaySec=5m

        [Install]
        WantedBy=timers.target
      ''; }
  ];
in
lib.mkIf (host.noRoot != null) {
  assertions = [{
    assertion = pkgs.stdenv.isLinux;
    message = "hosts.nix: noRoot is only supported on Linux (nix-portable)";
  }];

  home.homeDirectory = lib.mkForce cfg.home;
  # Jobs started outside the env (Slurm, cron) use the real home, so the
  # shared credentials go there too.
  dots.secrets = lib.mkMerge [
    (lib.mkIf (builtins.pathExists ../secrets/netrc.age) {
      netrc-real-home = { file = ../secrets/netrc.age; target = "${realHome}/.netrc"; };
    })
  ];
  # The real account's shell is the system zsh; inside the env use ours.
  home.sessionVariables.SHELL = zsh;
  # nix, hm-switch, nixshell, dots-pull
  home.sessionPath = [ bin ];

  home.activation.noRootEntrypoints = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    # ssh inside the env looks in <home>/.ssh; link the keys that exist in the
    # real home. (Done here, not via home.file: a store symlink to a missing
    # key breaks the build under nix-portable.)
    run mkdir -p ${cfg.home}/.ssh
    for k in id_rsa id_rsa.pub id_ed25519 id_ed25519.pub; do
      if [[ -e ${realHome}/.ssh/$k && ! -e ${cfg.home}/.ssh/$k ]]; then
        run ln -s ${realHome}/.ssh/$k ${cfg.home}/.ssh/$k
      fi
    done

    # Hand-written versions from before this module are kept once as *.pre-dotfiles.
    for f in nixshell nix hm-switch dots-pull; do
      if [[ -e ${bin}/$f ]] && ! grep -qs '${marker}' ${bin}/$f && [[ ! -e ${bin}/$f.pre-dotfiles ]]; then
        run cp -p ${bin}/$f ${bin}/$f.pre-dotfiles
      fi
      run install -m 755 ${scriptDir}/$f ${bin}/$f
    done

    run mkdir -p ${realHome}/.config/systemd/user
    for u in dots-sync.service dots-sync.timer; do
      run install -m 644 ${units}/$u ${realHome}/.config/systemd/user/$u
    done
    if [[ -x /usr/bin/systemctl ]] && /usr/bin/systemctl --user show-environment >/dev/null 2>&1; then
      run /usr/bin/systemctl --user daemon-reload
      run /usr/bin/systemctl --user enable --now dots-sync.timer
    else
      warnEcho "no systemd user session; dots-sync timer not enabled"
    fi
  '';
}
